### ISSUE TITLE
Querying dependecies

### ISSUE THREAD

**Issue by Ede123** [lazka/msys2-helpers#1]
Hi Christoph,

I'm just trying to figure out the best way to query dependencies for a given application (in my case to make it standalone, but I guess the process is the same as for any given MINGW-package). There seem to be a lot of possibilities and I'm having a hard time to figure out the most secure variant, so since you seem knowledgeable about this topic maybe you can help me out a bit:
* in your `dllcheck` command you're using `objdump -p` and then filter the output with the string `"DLL Name:"` which seems to work well but also a bit excessive.
* on Linux I learned people use `ldd`. The version shipping with MSYS2 does not seem to work well but there is also `mingw-w64-ntldd-git` by @LRN which seems to perform quite nicely when used with the recursive option (`ntldd -R`)
* last but not least I found `cygcheck` which is part of cygwin and seems to work perfectly for MINGW64 binaries (but apparently is broken for MINGW32 binaries?).

Any ideas on what method should be preferred to detect dependencies?

**Comment by lazka** [comment]
I have to admit I just tried a few things and used the easiest one where the result looked right to me.

What are you trying to do? Or what are you missing?

**Comment by Ede123** [comment]
I'm basically trying to find a solution to reliably check if all dependencies for an application (specifically Inkscape) were correctly copied to the distribution directory.

I'm not exactly missing anything, but want to figure out the most reliable (and ideally most elegant) solution for this purpose as there are a lot of options but none of them really seems to be tailored for this job.

My personal observations so far:
* cygcheck seems like the easiest. It automatically finds dependencies recursively and excludes a lot of noise from Microsoft libraries (`ext-ms-win-advapi32-registry-l1-1-0.dll` and similar) that is usually not required. Unfortunately I have to rule it out as it's broken for 32-bit executables.
* ntldd seems like the tool for the job. It also automatically finds dependencies recursively but includes all the noise from Microsoft libraries, so needs a lot of filtering to produce useful results. A minor downside is that it's an additional package.
* objdump seems like the "hard" way and does not recurse automatically but obviously seems to work quite well, too, if used correctly.

**Comment by lazka** [comment]
Feel free to improve it if you find any problems.

I'm using a similar script in quodlibet to detect missing libs and to delete the ones not referenced by anything and it worked well so far: https://github.com/quodlibet/quodlibet/blob/master/win_installer/misc/depcheck.py

With quodlibet we also use "installed tests" of some sorts where we use the installer to run our test suite which covers various things which could go wrong there like missing audio/video/image decoders etc. That's been really helpful in that I don't have to worry about basic things being broken due to packaging errors.

**Comment by Ede123** [comment]
I actually forgot to report back... (thanks for reminding me ;-) )

I decided to go with `ntldd` now as it automatically searches the path for dependencies. You can find the script I wrote at https://gitlab.com/inkscape/inkscape/blob/master/buildtools/msys2checkdeps.py.
It can be used to list dependencies for a single executable or a (distribution-)folder. It will show which libraries require a given dependency and can also be used in CI to check for missing or unnecessary libraries.

**Comment by lazka** [comment]
Cool, I'll give it a try.
